sonar.projectKey=fastapi-todos
sonar.projectName=FastApi Todos
sonar.sources=fastapi-app
sonar.exclusions=fastapi-app/myenv/**,fastapi-app/htmlcov/**,fastapi-app/templates/**,fastapi-app/tests/**
sonar.tests=fastapi-app/tests
sonar.python.coverage.reportPaths=fastapi-app/coverage.xml
sonar.sourceEncoding=UTF-8
